name: Compilar Código Java para EXE com jpackage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configurar JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Compilar Projeto Java
      run: |
        mkdir -p build
        javac -d build src/main/java/org/example/*.java

    - name: Criar JAR
      run: |
        jar cfm build/lfa.jar MANIFEST.MF -C build .

    - name: Criar EXE com jpackage
      run: |
        jpackage --input build --name lfa --main-jar build/lfa.jar --main-class org.example.Main.Class --type exe --dest build/

    - name: Fazer Upload dos Arquivos JAR e EXE
      uses: actions/upload-artifact@v4
      with:
        name: arquivos-compilados
        path: build/
