name: Compilar Código Java para EXE com GraalVM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configurar GraalVM
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'graalvm'

    - name: Instalar Native Image
      run: |
        gu install native-image

    - name: Compilar Projeto Java
      run: |
        mkdir -p build
        javac -d build src/**/*.java  # Compilar os arquivos Java
        
    - name: Criar Arquivo JAR
      run: |
        REPO_NAME=$(basename ${{ github.repository }})
        jar cvf build/$REPO_NAME.jar -C build .

    - name: Compilar para Imagem Nativa (EXE)
      run: |
        REPO_NAME=$(basename ${{ github.repository }})
        native-image --no-fallback -H:Name=build/$REPO_NAME --enable-all-security-services --verbose -cp build/$REPO_NAME.jar

    - name: Fazer Upload dos Arquivos JAR e EXE
      uses: actions/upload-artifact@v4
      with:
        name: arquivos-compilados
        path: build/
