name: Compilar Código Java para EXE com jpackage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configurar JDK Temurin 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Usando Temurin 11
        distribution: 'adoptopenjdk'

    - name: Compilar Projeto Java
      run: |
        mkdir -p build
        javac -d build src/**/*.java  # Compilar os arquivos Java

    - name: Criar JAR
      run: |
        REPO_NAME=$(basename ${{ github.repository }})
        jar cvf build/$REPO_NAME.jar -C build .

    - name: Criar EXE com jpackage
      run: |
        REPO_NAME=$(basename ${{ github.repository }})
        jpackage --input build --name $REPO_NAME --main-jar $REPO_NAME.jar --main-class your.main.Class --type exe --dest build/

    - name: Fazer Upload dos Arquivos JAR e EXE
      uses: actions/upload-artifact@v4
      with:
        name: arquivos-compilados
        path: build/
