name: Compile Java Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8' # Or specify the version you need

    - name: Build Java Project
      run: |
        mkdir -p build
        javac -d build src/main/java/org/example/*.java # Assuming your code is under `src/` folder
        
    - name: Create JAR file
      run: |
        jar cfm build/$(basename ${{ github.repository }}).jar MANIFEST.MF -C build .

    - name: Download Launch4j
      run: |
        curl -L -o launch4j.zip https://github.com/launch4j/launch4j/releases/download/3.15/launch4j-3.15-linux-x64.tar.gz
        tar -xvzf launch4j.zip

    - name: Generate EXE with Launch4j
      run: |
        java -jar launch4j/launch4j-3.15/launch4j --jar build/$(basename ${{ github.repository }}).jar --outfile build/$(basename ${{ github.repository }}).exe --icon icon.ico
        
    - name: Upload JAR and EXE as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-files
        path: build/
